### ISSUE TITLE
KA-Lite install

### ISSUE THREAD

**Issue by yohanboniface** [ideas-box/ideasbox-scripts#1]
We need a clean way to:
- install KA-Lite
- upgrade KA-Lite
- download videos according to box languages
- update videos

They have plans to release a Debian package, but not in the timeline of our next box release: https://github.com/learningequality/installers/issues/1#issuecomment-66509668

One important point: application data (users, scores, etc.) must be in the backuped directory of the box, including the database, which is a SQLite. But the videos must not be in the backuped folder.

**Comment by yohanboniface** [comment]
There is now a .deb and a ppa for KA lite! Let's use it :)
https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite

**Comment by letompouce** [comment]
This repository is now abandoned in favour of
[ansiblecube](https://github.com/ideascube/ansiblecube).
