### ISSUE TITLE
Network configuration

### ISSUE THREAD

**Issue by Geam** [ideas-box/ideasbox-scripts#2]
We need a way to install and configure the network part of the server. We want : 
- a wifi hotspot for the tablets
- a DHCP for the wifi hotspot
- a dns to be able to reach the server without typing his IP address
- an ssh acces to the server

**Comment by yohanboniface** [comment]
BTW, we need even some subdomains to be mapped:
- wikipedia.ideasbox.lan => kiwix
- khan.ideasbox.lan => ka-lite
- map.ideasbox.lan => openstreetmap map (when we have it)

Not sure at this point if *.ideasbox.lan should point to an nginx/apache virtual host, which then remap this to every service, or if we have a nginx/apache vhost by subdomain, or if we directly map every service. And not sure how not to hard code each service port.

**Comment by letompouce** [comment]
This repository is now abandoned in favour of
[ansiblecube](https://github.com/ideascube/ansiblecube).
