### ISSUE TITLE
Kiwix install

### ISSUE THREAD

**Issue by yohanboniface** [ideas-box/ideasbox-scripts#4]
We need:
- an easy way to install the kiwix server (Debian package ideally)
- an easy way to download ZIM for selected languages (each box will have its own languages), at install time but also for upgrade from time to time
- an easy way to index/reindex installed ZIM
- a way to start/stop/restart server using service API

Reference: http://www.kiwix.org/wiki/Kiwix-serve

**Comment by yohanboniface** [comment]
Doesn't seem to have any Debian package available: http://www.kiwix.org/wiki/Debian

**Comment by yohanboniface** [comment]
From IRC discussion, this seem to be the link that always point to an up to date version: http://download.kiwix.org/bin/kiwix-server-arm.tar.bz2

**Comment by yohanboniface** [comment]
Plan B? https://github.com/braddockcg/internet-in-a-box/blob/master/iiab/zimpy.py

**Comment by yohanboniface** [comment]
Also: https://github.com/pediapress/pyzim

**Comment by rodo** [comment]
@hashar any hints you can give to us to help on this issue ? Thx

**Comment by yohanboniface** [comment]
ping @kelson42 too :)

**Comment by hashar** [comment]
I have no idea how kiwix works sorry. But @kelson42 definitely does :-}

**Comment by kelson42** [comment]
I thought all that job has already been done!

Here a few answers:
- an easy way to install the kiwix server (Debian package ideally)
  -> http://www.kiwix.org/wiki/Software have permalinks to the statically compiled versions (just unzip and use)
- an easy way to download ZIM for selected languages (each box will have its own languages), at install time but also for upgrade from time to time
  -> http://www.kiwix.org/wiki/Content_in_all_languages here again we have permalinks, use the "portable version".
- an easy way to index/reindex installed ZIM
  -> You don't need this if you download portable versions
- a way to start/stop/restart server using service API
  -> Just create a primitive service script with 'kill' for stop.

XSCE has created an admin tool to do this and this is done in Python. Here a twitt:
https://twitter.com/KiwixOffline/status/630391985568919552

Hope that helps.

**Comment by letompouce** [comment]
This repository is now abandoned in favour of
[ansiblecube](https://github.com/ideascube/ansiblecube).
