### ISSUE TITLE
Always add date when backuping files

### ISSUE THREAD

**Issue by yohanboniface** [ideas-box/ideasbox-scripts#7]
Now we create a `.back` copy, so if we run the install twice we lose the original

**Comment by rodo** [comment]
@yohanboniface could you add a link to the script involved in this issue ?

**Comment by yohanboniface** [comment]
No sure this is still valid, since @fheslouin has worked on Ansible deployement process (dunno where the sources are though :/).

In case, I'm referencing this kind of thing: https://github.com/ideas-box/ideasbox-scripts/blob/master/hostapd/install.sh#L59

**Comment by rodo** [comment]
It seems it was fixed, just a hint, I prefer to use `date +%u` to keep the last 7 backups and avoid to deal with old backup purge.

**Comment by letompouce** [comment]
This repository is now abandoned in favour of
[ansiblecube](https://github.com/ideascube/ansiblecube).
